# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'tkradm@yahoo.fr'
  config.password       = ENV['DOCUSIGN_PASSWORD']
  config.integrator_key = '979a64f3-6077-4354-8fe7-d9d6417f98fe'
  config.account_id     = '11962701'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v2'
end

