name: Tests

on:
  push:
  pull_request_target:
    branches:
      - 'dependabot/*'
    types:
      - opened
# jobs:
#   cleanup-runs:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: rokroskar/workflow-run-cleanup-action@master
#         env:
#           GITHUB_TOKEN: "${{ secrets.GH_ACCESS_TOKEN }}"
#         if: "github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/production'"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6

      - name: Cache bundle
        uses: actions/cache@v1
        env:
          cache-name: bundle
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ env.cache-name }}-${{ hashFiles('**/Gemfile.lock') }}

      - name: Install dependencies
        run: |
          bundle install --path=vendor/bundle --jobs 4 --retry 3
          yarn install

      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          rake "db:check_segment_files[${{ steps.abc.outputs.all }}]"
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.abc.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.abc.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.abc.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"
